### PR TITLE
feat(shortcuts): add shortcut for SunCalc

### PR DESCRIPTION
**Pull request by P3run**
I swear this is the last one ;). In this case I had to introduce two additional parameters - date and time. Without them SunCalc displays the error message and then ignores zoom settings. I know that it would be better not to add them but I couldn't find any other solution.

### CODE REVIEW

**Review by haruspeks — CHANGES_REQUESTED** [review]
There's a way to force a default to the current day and time without having to specify it: in [the docs](https://www.torsten-hoffmann.de/apis/suncalcmooncalc/link_en.html) it specifies that the literal value "null" can be used instead. Not the behavior I'd expect, but it actually works: https://suncalc.org/#/50.8421,4.3781,17/null/null/null/3

**Comment by P3run** [comment]
Oh, shame on me! I didn't check the docs. I will fix it today evening. Thanks!

**Comment by P3run** [comment]
Okay, I found a minute to do that now ;). Done.

**Comment by haruspeks** [comment]
All good :) Merged. 

I will publish a new release with all the recent changes.

**Pull request merged**
